### ISSUE TITLE
2 button

### ISSUE THREAD

**Issue by geva-elettronica** [alextaujenis/RBD_HumanSensor#2]
Adding 2 buttons, all stop working

**Comment by alextaujenis** [comment]
Hi @gioreva,

I don't really have anything to work with here to help you. If you are still having a problem: please try re-opening this issue with a description of what you are trying to accomplish, what hardware you are using in your project, how you have wired your components together, and what code you are running.

Try to follow the wiring diagram and example code found here: https://robotsbigdata.com/docs-arduino-human-sensor.html#example-wiring

You can create multiple instances of this library (for multiple touch sensors) like this: 

```C++
#include <RBD_Capacitance.h>
#include <RBD_Threshold.h>
#include <RBD_HumanSensor.h>
 
RBD::HumanSensor human_sensor_one(2, 3); // send, receive pin
RBD::HumanSensor human_sensor_two(4, 5); // send, receive pin
 
void setup() {
  Serial.begin(115200);
}
 
void loop() {
  human_sensor_one.update();
  human_sensor_two.update();
 
  if(human_sensor_one.onRawValueChange()) {
    Serial.println(human_sensor_one.getRawValue());
  }
  if(human_sensor_two.onRawValueChange()) {
    Serial.println(human_sensor_two.getRawValue());
  }
}
```
